
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 23 12:25:30 CEST 2021
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ENTER = 2;
  public static final int ABREPARENT = 4;
  public static final int DOSPUNTOS = 9;
  public static final int ACREGISTRO = 17;
  public static final int CONST = 28;
  public static final int RESTA = 10;
  public static final int INTEGER = 32;
  public static final int PUNTOCOMA = 8;
  public static final int WRITEINT = 44;
  public static final int ARRAY = 26;
  public static final int FOR = 30;
  public static final int CIERCORCHE = 7;
  public static final int AND = 25;
  public static final int IGUAL = 13;
  public static final int RECORD = 36;
  public static final int TYPE = 41;
  public static final int FI = 22;
  public static final int BEGIN = 21;
  public static final int WRITELN = 45;
  public static final int IF = 31;
  public static final int CIERPARENT = 5;
  public static final int ID = 19;
  public static final int OF = 34;
  public static final int EOF = 0;
  public static final int BOOLEAN = 24;
  public static final int RETURN = 37;
  public static final int PRODUCTO = 11;
  public static final int error = 1;
  public static final int FALS = 29;
  public static final int COMA = 20;
  public static final int NEGACION = 15;
  public static final int ASIGNACION = 16;
  public static final int MAYOR = 12;
  public static final int MODULE = 33;
  public static final int LITERAL = 3;
  public static final int ELSE = 27;
  public static final int WRITESTRING = 43;
  public static final int TO = 39;
  public static final int THEN = 38;
  public static final int ABRECORCHE = 6;
  public static final int CERT = 40;
  public static final int ACVECTOR = 18;
  public static final int DISYUNCION = 14;
  public static final int VAR = 42;
  public static final int PROCEDURE = 35;
  public static final int DO = 23;
}

